version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/appuser/static_cdn/static_root/
      - mediafiles:/home/appuser/static_cdn/media_root/
    depends_on:
      - web
  web:
    container_name: django
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: >
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=4
    env_file:
      - .env.prod
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/appuser/static_cdn/static_root/
      - mediafiles:/home/appuser/static_cdn/media_root/
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    env_file:
      - .env.db.prod
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  staticfiles:
  mediafiles:
