version: '3.8'

services:
  web:
    container_name: django-api
    build: src/
    command: >
      python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./src/:/home/appuser/webapp/
      - ./static_cdn/static_root/:/home/appuser/static_cdn/static_root/
      - ./static_cdn/media_root/:/home/appuser/static_cdn/media_root/

  celery:
    container_name: celery-api
    build: src/
    command: >
      celery -A core worker -l INFO
    env_file:
      - .env
    depends_on:
      - web
      - redis
    volumes:
      - ./src/:/home/appuser/webapp/
      - ./static_cdn/static_root/:/home/appuser/static_cdn/static_root/
      - ./static_cdn/media_root/:/home/appuser/static_cdn/media_root/

  adminer:
    container_name: adminer-api
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  db:
    container_name: postgresdb-api
    image: postgres:latest
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-api:/var/lib/postgresql/data

  redis:
    container_name: redis-api
    image: redis:alpine

volumes:
  postgres-data-api:
