# Generated by Django 3.2.5 on 2021-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(default='benim'),
            preserve_default=False,
        ),
    ]
